# Generated by Django 4.1.2 on 2024-01-30 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('guid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('test_mode', models.IntegerField(choices=[(1, 'En línea'), (2, 'Fuera de línea'), (3, 'Desarrollo')], verbose_name='Mode')),
                ('is_mobile', models.BooleanField(default=False, verbose_name='Is mobile')),
                ('browser', models.CharField(blank=True, max_length=30, null=True, verbose_name='Browser')),
                ('operating_system', models.CharField(blank=True, max_length=30, null=True, verbose_name='Operating system')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('contact', models.CharField(blank=True, max_length=100, verbose_name='Contact')),
                ('sex', models.CharField(choices=[('Male', 'Hombre'), ('Female', 'Mujer'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=10, verbose_name='Sex')),
                ('ethnicity', models.CharField(choices=[('White', 'Blanca'), ('Black', 'Afro o negra'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=10, verbose_name='Ethnicity')),
                ('deaf_community', models.CharField(choices=[('Yes', 'Si'), ('No', 'No'), ('N/A', 'Prefiero no responder')], max_length=5, verbose_name='Deaf community')),
                ('birthdate', models.CharField(max_length=4, verbose_name='Birthdate')),
                ('birthplace', models.CharField(choices=[('South', 'Sur (Montevideo o Canelones)'), ('West', 'Oeste (San José, Soriano, Colonia o Río Negro)'), ('Center', 'Centro (Durazno, Flores, Florida o Lavalleja)'), ('North', 'Norte (Artigas, Salto, Paysandú, Tacuarembó o Rivera)'), ('East', 'Este (Rocha, Maldonado, Cerro Largo o Treinta y Tres)'), ('Argentina', 'Argentina'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=10, verbose_name='Birthplace')),
                ('education', models.CharField(choices=[('School', 'Escuela'), ('First Cycle', 'Educación media básica (3º de liceo terminado o similar)'), ('Secondary education', 'Educación media superior (6º de liceo terminado o similar)'), ('Tertiary education', 'Educación terciaria (tecnicatura, diplomatura o grado universitario)'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=30, verbose_name='Education')),
                ('school', models.CharField(choices=[('Common school', 'Escuela común'), ('Deaf class', 'Clase para sordos en una escuela común'), ('Bilingual school', 'Escuela bilingüe (Nº 197 de Montevideo, Nª 84 de Maldonado, Nº 105 de Rivera, Nª 116 de Salto)'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=20, verbose_name='School')),
                ('age_of_acquisition', models.CharField(choices=[('Birth', 'De nacimiento'), ('<6', 'Antes de los 6 años'), ('<12', 'Antes de los 12 años'), ('<18', 'Antes de los 18 años'), ('18>', 'Después de los 18 años'), ('N/A', 'Prefiero no responder')], max_length=5, verbose_name='Age of Acquisition')),
                ('language_at_home', models.CharField(choices=[('LSU', 'LSU'), ('Spanish', 'Español'), ('Gestures', 'Mímica'), ('Fingerspelling', 'Deletreo'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], max_length=20, verbose_name='Language at home')),
                ('lsu_fluency', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='LSU fluency')),
                ('preferred_language', models.CharField(choices=[('LSU', 'LSU'), ('Spanish', 'Español'), ('Other', 'No me identifico con estas opciones'), ('N/A', 'Prefiero no responder')], default='N/A', max_length=20, verbose_name='Preferred language')),
            ],
            options={
                'verbose_name': 'Form',
                'verbose_name_plural': 'Forms',
            },
        ),
        migrations.CreateModel(
            name='Stimulus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=50, verbose_name='Term')),
                ('file_name', models.CharField(max_length=50, verbose_name='Filename')),
            ],
            options={
                'verbose_name': 'Stimulus',
                'verbose_name_plural': 'Stimuli',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('familiarity', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(7)], verbose_name='Familiarity')),
                ('rt', models.IntegerField(blank=True, null=True, verbose_name='Response time')),
                ('te', models.IntegerField(blank=True, null=True, verbose_name='Time elapsed')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='frequencies.form', verbose_name='Form')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frequencies.stimulus', verbose_name='Stimulus')),
            ],
            options={
                'verbose_name': 'Reply',
                'verbose_name_plural': 'Replies',
                'unique_together': {('form', 'stimulus')},
            },
        ),
    ]
